### ISSUE TITLE
Is the TAVGBench dataset available?

### ISSUE THREAD

**Issue by pilzner** [OpenNLPLab/TAVGBench#1]
Are the generated audio, video and audio-visual captions for your TAVGBench unavailable just for now, or will it be proprietary?
Access to this benchmark seems pretty crucial for comparisons with your baseline, as well as being very useful for other audio-visual tasks.

**Comment by MaoYuxin25** [comment]
Thank you for your attention. The data set, code and trained model will be open sourced later.

**Comment by MaoYuxin25** [comment]
Hello, the annotation of TAVGBench has been open sourced. Please download it in the readme!
