### ISSUE TITLE
data release

### ISSUE THREAD

**Issue by kail8** [OpenNLPLab/TAVGBench#3]
Hi, TAVGBench is an impressive work that can greatly promote the video-audio joint generation in the community. But it seems that you only release the annotation file for your training data. Will the source data (video-audio pairs) be released too?

**Comment by MaoYuxin25** [comment]
Hello, thank you for your attention to our work. The original data comes from audioset. Due to copyright reasons, we cannot share it. You can obtain this data according to the download process of audioset.

**Comment by kail8** [comment]
Hi, thanks again for your contribution to the community. I have another question. According to your paper, the released text descriptions are merged from paired audio and video captions. Do you plan also to release the separated captions for each single modality? I think they are also valuable in exploring synchronized video and audio generation.

**Comment by MaoYuxin25** [comment]
Thanks for your attention, this is an interesting idea. It will take us some time to find and retrieve the original annotations.
